### PR TITLE
change requirements to pypi format, remove ESP32SPI requirement

### PR DESCRIPTION
**Pull request by Neradoc**
While pypi doesn't care about `-` versus `_` and letter case, the format used for the minimqtt requirement makes it listed in "external_dependencies" instead of "dependencies" in the bundle's json file, causing potential issues with bundler tools.
And the library does not need ESP32SPI, it works on native wifi too.

### CODE REVIEW

**Review by tekktrik — CHANGES_REQUESTED** [review]
Looks like there's a CI error, but if same thing as the other PR - if any of the dependencies are used in optional functionalities or examples, could you add them to a new `optional_requirements.txt`?  Thanks!

**Comment by Neradoc** [comment]
The error is from the docs run, because of the type annotations that use ESP32SPI. But if it works with native we don't want circup or others installing the ESP32SPI library. Projects that require the esp library will import it regardless of whether it's a requirement for LIFX or not.
So I added it back to setup.py.
I suppose that will be handed by the optional requirements in the future ?

**Comment by Neradoc** [comment]
Also moved `adafruit-circuitpython-esp-atcontrol` to optional_requirements.txt

**Comment by tekktrik** [comment]
Trying to figure out how to type annotate something using `type()` without using said type is rough haha.  Here's one solution with a few steps:

Add a type definition to `adafruit_requests`:

```python
class WiFiManagerProtocol(Protocol):

    def post(url: str, **kwargs) -> Response:
        """Post method"""

    def put(url: str, **kwargs) -> Response:
        """Put method"""

    def get(url: str, **kwargs) -> Response:
        """Get method"""

        ...
```

Then, we can pull it in this library and modify it:

```python
from typing import Union
from adafruit_requests import WiFiManagerProtocol, Session

ESP32SPI_WFM_Type = type("ESPSPI_WiFiManager", (), {})
ESPAT_WFM_Type = type("ESPAT_WiFiManager", (), {})

AllowedWiFiManagerProtocol(WiFiManagerProtocol):

    __class__: Union[Type[ESP32SPI_WFM_Type], Type[ESPAT_WFM_Type]]

AllowedWiFiManagerType = Union[AllowedWiFiManagerProtocol, Session]

```

I think `AllowedWiFiManagerType` is good then:

```python
    def __init__(self, wifi_manager: AllowedWifiManagerType, lifx_token: str) -> None:
```

OOOORRRR we just remove the type annotation :laughing: I'm open to that since the docstring is pretty clear

**Comment by Neradoc** [comment]
That's a lot of hoops to jump through to get to that !
I suppose there is something to be said about having a unified "network manager" type.

**Comment by tekktrik** [comment]
The more I think about this more I think a general `Protocol` is useful, but not the code I had mentioned that was specific to this library.  I think the docstring can just specify *which* specific classes that fit that mold are accepted.  How does that sound?  I can PR that change to `circuitpython_typing` if it sounds good.

**Comment by FoamyGuy** [comment]
> I can PR that change to `circuitpython_typing` if it sounds good.

This idea sounds good to me if you're still interested in PR'ing that in the typing library so it can be used here (and elsewhere as needed). 

Mabye `HTTPProtocol` as a name? I think that is what defines all of those different types of requests.

**Comment by tekktrik** [comment]
Definitely happy to do that!

**Comment by tekktrik** [comment]
Okay, I'll make a new PR for the changes discussed here, but this looks good to me!  I merged `main` into this so I can merge it :)

**Comment by tekktrik** [comment]
Oh hey, it actually looks like the `pyproject.toml` migration fixed the issue, thanks y'all!

**Pull request closed without merging**
